# site settings
title: Alireza Farokhi
description: Welcome to my portfolio website
email: iqstudiotehran@gmail.com
taglong: Alireza Farokhi's online CV
tagshort: Alireza Farokhi
url: "https://alireza-farokhi.github.io/"
baseurl: ""
permalink: pretty
twitter_username: alirezFar
github_username:  alireza-farokhi
linkedin_username: alireza-farokhi
stackoverflow_username: 8045491/alireza-farokhi

# author settings
author:
  name: Alireza Farokhi
  email: iqstudiotehran@gmail.com
photo: /assets/jpg/Alireza-Farokhi.jpg

# build settings

exclude:
  - LICENSE
  - README.md

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap

whitelist:
  - jekyll-sitemap

sass:
  sass_dir: _sass
  style: compressed
  sourcemap: never

feed:
  path: atom.xml

autopages:
  enabled: false

pagination:
  enabled: true
  per_page: 1
  sort_reverse: true
  permalink: /:num/
  title: ":title &middot; Page :num"
